config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("entry_form.urls")),
]

entry_form/urls.py
from django.urls import path
from . import views

app_name = "datefield"
urlpatterns = [
    path('', views.begin_entry),
    path('entry-form', views.entry_form , name="entry_form")
]

entry_form/models.py
from django.db import models
from django_countries.fields import CountryField


class Entrant(models.Model):
    GENDERS = [
        ("male", "Male"),
        ("female", "Female"),
    ]
    EDUCATION_LEVELS = [
        ("primary school only", "Primary school only"),
        ("high school, no degree", "High School, no degree"),
        ("high shool degree", "High School degree"),
        ("vocational shool", "Vocational School"),
        ("some university courses", "Some University Courses"),
        ("university degree", "University Degree"),
        ("some graduate level courses", "Some Graduate Level Courses"),
        ("master's degree", "Master's Degree"),
        ("some doctorate level courses", "Some Doctorate Level Courses"),
        ("doctorate degree", "Doctorate Degree"),
    ]
    MARITAL_STATUS = [
        ("unmarried", "Unmarried"),
        ("married_nlpr", "Married and my spouse is NOT a U.S. citizen or U.S. Lawful Permanent Resident (LPR)"),
        ("married_lpr", "Married and my spouse is a U.S. citizen or U.S. Lawful Permanent Resident (LPR)"),
        ("divorced", "Divorced"),
        ("widowed", "Widowed"),
        ("legally separated", "Legally Separated"),
    ]

    last_name = models.CharField("Last/Family Name", max_length=33)
    first_name = models.CharField("First Name", max_length=33)
    middle_name = models.CharField("Middle Name", max_length=33, null=True)
    gender = models.CharField(max_length=6, choices=GENDERS)
    birth_date = models.DateField(blank=True)
    birth_city = models.CharField("Birth City", max_length=33)
    birth_country = CountryField(blank_label="Select A Country...")
    eligibility_country = CountryField(blank_label="Select A Country...")
    entrant_photograph = models.ImageField(upload_to="")
    mailing_address_in_care_of = models.CharField("In Care Of (optional)", max_length=33, null=True, blank=True)
    mailing_address_address_line_one = models.CharField("Address Line 1", max_length=33)
    mailing_address_address_line_two = models.CharField("Address Line 2 (optional)", max_length=33, null=True, blank=True)
    mailing_adress_city = models.CharField("City/Town", max_length=50)
    mailing_adress_provence = models.CharField("District/County/Province/State", max_length=50)
    mailing_address_zip_code = models.CharField("Postal Code/Zip Code", max_length=33)
    mailing_address_country = CountryField("Country", blank_label="Select A Country...")
    resident_country = CountryField(blank_label="Select A Country...")
    phone_number = models.PositiveBigIntegerField(null=True, blank=True)
    e_mail = models.EmailField()
    education_level = models.CharField(max_length=33, choices=EDUCATION_LEVELS)
    marital_status = models.CharField(max_length=20, choices=MARITAL_STATUS)
    number_of_children = models.PositiveSmallIntegerField()
    confirmation_number = models.CharField(max_length=16, blank=True)
    digital_signature = models.CharField(max_length=40, blank=True)
    

entry_form/forms.py
from django import forms
from . import models

class EntrantForm(forms.ModelForm):
    month = forms.IntegerField(min_value=1, max_value=12)
    day = forms.IntegerField(min_value=1, max_value=31)
    year = forms.IntegerField(min_value=1907, max_value=2015)
    
    class Meta:
        model = models.Entrant
        fields = "__all__"
        widgets = {
            "gender": forms.RadioSelect,
            "education_level": forms.RadioSelect,
            "marital_status": forms.RadioSelect,
        }

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(EntrantForm, self).__init__(*args, **kwargs)

entry_form/views.py
from django.shortcuts import render
from . import models
from . import forms
import datetime


def begin_entry(request):
    return render(request, 'entry_form/begin_entry.html')

def entry_form(request):
    if request.method == "POST":
        pass

    form = forms.EntrantForm()
    return render(request, "entry_form/entry_form.html", {
        "form": form,
    })    

entry_form/templates/entry_form/begin_entry.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <meta name="description" content="You want to sign up for the DV Visa? Start here.">
    <link rel="stylesheet" href="{% static "entry_form/articles.css" %}">
    <style>
        body {
            text-align: center;
        }
        
        a {
            display: inline-block;
            margin: 9px 0;
            padding: 0.375rem 0.75rem;
            background-color: #3e8f3e;
            background-image: linear-gradient(to bottom, #5cb85c 0, #419641 100%);
            background-repeat: repeat-x;
            border: 1px solid transparent;
            border-radius: 0.25rem;
            text-decoration: none;
            color: white;
        }

        a:hover {
            background-image: none;
        }

    </style>
{% endblock %}

{% block body %}
    <article class="card">
        <div class="card-header">
            <h4>Entry Form</h4>
        </div>
        <div class="card-body">
            <p>The entry form is prepared in two parts, one for the primary Entrant and one for derivatives (if any). Each part must be completed correctly and completely before going to the next part. After all parts are completed, the entry will be submitted to the DV-202X Processing Center. Click the link below to begin the entry process.</p>
            <a href="{% url "datefield:entry_form" %}">Begin Entry</a>
        </div>
    </article>
{% endblock %}

entry_form/templates/entry_form/entry_form.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <meta name="description" content="The DV-202X Entry Form.">
    <link rel="stylesheet" href="{% static "entry_form/articles.css" %}">
{% endblock %}

{% block body %}
<h1>Part One - Entrant Information</h1>
<form action="" method="POST">
    {% csrf_token %}

    <article class="card">
        <div class="card-header">
            <h4>1. Name</h4>
        </div>
        <div class="card-body flex-container">
            <div>
                {{ form.last_name.label_tag }}
                <br>
                {{ form.last_name }}
            </div>
            <div>
                {{ form.first_name.label_tag }}
                <br>
                {{ form.first_name }}
            </div>
            <div>
                {{ form.middle_name.label_tag }}
                <br>
                {{ form.middle_name }}
            </div>
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>2. Gender</h4>
        </div>
        <div class="card-body">
            {% for radio in form.gender %}
            {% if radio.id_for_label != "id_gender_0" %}
                {{ radio.tag }}
                {{ radio.choice_label }}
            {% endif %}
            {% endfor %}
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>3. Birth Date</h4>
        </div>
        <div class="card-body flex-container">
            <div>
                {{ form.birth_month.label_tag }}
                <br>
                {{ form.birth_month }}
            </div>
            <div>
                {{ form.birth_day.label_tag }}
                <br>
                {{ form.birth_day }}
            </div>
            <div>
                {{ form.birth_year.label_tag }}
                <br>
                {{ form.birth_year }}
            </div>
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>4. City Where You Were Born</h4>
        </div>
        <div class="card-body">
            <div>
                {{ form.birth_city.label_tag }}
                <br>
                {{ form.birth_city }}
            </div>
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>5. Country Where You Were Born</h4>
        </div>
        <div class="card-body">
            <div>
                {{ form.birth_country.label_tag }}
                <br>
                {{ form.birth_country }}
            </div>
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>6. Country of Eligibility for the DV Program</h4>
        </div>
        <div class="card-body">
            <div>
                {{ form.eligibility_country.label_tag }}
                <br>
                {{ form.eligibility_country }}
            </div>
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>7. Entrant Photograph</h4>
        </div>
        <div class="card-body">
            {{ form.entrant_photograph }}
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>8. Mailing Address</h4>
        </div>
        <div class="card-body">
            <div>
                a. {{ form.mailing_address_in_care_of.label_tag }}
                <br>
                {{ form.mailing_address_in_care_of }}
            </div>
            <div>
                b. {{ form.mailing_address_address_line_one.label_tag }}
                <br>
                {{ form.mailing_address_address_line_one }}
            </div>
            <div>
                c. {{ form.mailing_address_address_line_two.label_tag }}
                <br>
                {{ form.mailing_address_address_line_two }}
            </div>
            <div>
                d. {{ form.mailing_adress_city.label_tag }}
                <br>
                {{ form.mailing_adress_city }}
            </div>
            <div>
                e. {{ form.mailing_adress_provence.label_tag }}
                <br>
                {{ form.mailing_adress_provence }}
            </div>
            <div>
                f. {{ form.mailing_address_zip_code.label_tag }}
                <br>
                {{ form.mailing_address_zip_code }}
            </div>
            <div>
                g. {{ form.mailing_address_country.label_tag }}
                <br>
                {{ form.mailing_address_country }}
            </div>
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>9. Country Where You Live Today</h4>
        </div>
        <div class="card-body">
            <div>
                {{ form.resident_country }}
            </div>
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>10. Phone Number</h4>
        </div>
        <div class="card-body">
            <div>
                {{ form.phone_number }}
            </div>
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>11. E-mail Address</h4>
        </div>
        <div class="card-body">
            <div>
                {{ form.e_mail }}
            </div>
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>12. What is the highest level of education you have achieved, as of today?</h4>
        </div>
        <div class="card-body">
            {% for radio in form.education_level %}
            {% if radio.id_for_label != "id_education_level_0" %}
                <div>
                    {{ radio.tag }}
                    {{ radio.choice_label }}
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>13. What is your current marital status?</h4>
        </div>
        <div class="card-body">
            {% for radio in form.marital_status %}
            {% if radio.id_for_label != "id_marital_status_0" %}
                <div>
                    <!-- {{ radio.id_for_label }} -->
                    {{ radio.tag }}
                    {{ radio.choice_label }}
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </article>
    
    <article class="card">
        <div class="card-header">
            <h4>14. Number of Children</h4>
        </div>
        <div class="card-body">
            <div>
                {{ form.number_of_children }}
            </div>
        </div>
    </article>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Sina Arasteh">
    <meta name="generator" content="Django framwork">
    <meta name="application-name" content="Electronic Diversity Visa Entry Form">
    <title>Electronic Diversity Visa Program</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>